name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build-on-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.15.0
        uses: actions/setup-node@v1
        with:
          node-version: "14.15.0"
      - name: Install node_modules
        run: |
          npm i -s
          npm install -g @angular/cli
      - name: Build
        run: ng build --prod --outputHashing none
      - name: Push to ghpages as test
        run: npx angular-cli-ghpages --dir=dist/aktools --repo=https://$TOKEN@$REPO --no-silent --branch=gh-pages --email=$EMAIL --cname=$CNAME --name=graueneko --message "$(date '+%Y-%m-%d %H:%M:%S')"
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: github.com/graueneko/aktools-bigfun.git
          PROJECT: aktools
          CNAME: aktoolsbf.test.graueneko.com
      - name: Push to Gitee
        run: |
          # npm run-script build
          bash ./postbuild.sh
          npx angular-cli-ghpages --dir=dist/ --repo=https://$TOKEN@$REPO --no-silent --branch=master --email=$EMAIL --name=graueneko --message "$(date '+%Y-%m-%d %H:%M:%S')"
        env:
          TOKEN: ${{ secrets.GITEE_TOKEN }}
          REPO: gitee.com/coder_1024/aktools.git
      - name: Send status message
        if: always()
        uses: yanzay/notify-telegram@v0.1.0
        with:
          chat: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          status: ${{ job.status }}
    env:
      CI: true
      EMAIL: graueneko@gmail.com
