name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build-on-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.15.3
        uses: actions/setup-node@v1
        with:
          node-version: "10.15.3"
      - name: Install node_modules
        run: |
          npm i -s
          npm install -g @angular/cli
      - name: Build & deploy coding-pages
        run: |
          npm run-script build
          npx angular-cli-ghpages --dir=dist/ --repo=https://$TOKEN@$REPO --no-silent --branch=master --message "$(date '+%Y-%m-%d %H:%M:%S')"
        env:
          TOKEN: ${{ secrets.GITEE_TOKEN }}
          REPO: gitee.com/coder_1024/aktools.git
    env:
      CI: true
      PROJECT: aktools
      EMAIL: graueneko@gmail.com
