name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build-on-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.15.3
        uses: actions/setup-node@v1
        with:
          node-version: "10.15.3"
      - name: Install node_modules
        run: |
          npm i -s
          npm install -g @angular/cli
      - name: Publish to Gitee
        run: |
          npm run-script build
          npx angular-cli-ghpages --dir=dist/ --repo=https://$TOKEN@$REPO --no-silent --branch=master --email=graueneko@gmail.com --name=graueneko --message "$(date '+%Y-%m-%d %H:%M:%S')"
        env:
          TOKEN: ${{ secrets.GITEE_TOKEN }}
          REPO: gitee.com/coder_1024/aktools.git
      - name: Send failure message
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: Fail on aktools-bigfun build & push
      - name: Send success message
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: Succ on aktools-bigfun build & push
    env:
      CI: true
      PROJECT: aktools
      EMAIL: graueneko@gmail.com
      Done! Congratulations on your new bot. You will find it at t.me/grauenekobot. You can now add a description, about section and profile picture for your bot, see /help for a list of commands. By the way, when you've finished creating your cool bot, ping our Bot Support if you want a better username for it. Just make sure the bot is fully operational before you do this.

Use this token to access the HTTP API:
1135328691:AAF0GktiyT_YL9fnxT8yUTBC0fAeHDbKnTc
Keep your token secure and store it safely, it can be used by anyone to control your bot.

For a description of the Bot API, see this page: https://core.telegram.org/bots/api
